packages:
  - "."

overrides:
  cookie: ^0.7.2
  find-my-way: ^9.7.0
  valibot: ^1.4.2

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - '@prisma/adapter-better-sqlite3@7.9.1'
  - '@prisma/client-runtime-utils@7.9.1'
  - '@prisma/client@7.9.1'
  - '@prisma/config@7.9.1'
  - '@prisma/debug@7.9.1'
  - '@prisma/dev@0.24.17'
  - '@prisma/driver-adapter-utils@7.9.1'
  - '@prisma/engines@7.9.1'
  - '@prisma/fetch-engine@7.9.1'
  - '@prisma/get-platform@7.9.1'
  - prisma@7.9.1
