import mysql from 'mysql2/promise';
import crypto from 'crypto';
import type { DatabaseHost, ServerDatabase } from '../../../generated/prisma/client';

const IDENTIFIER_RE = /^[A-Za-z0-9_]+$/;
const GENERATED_PASSWORD_RE = /^[0-9a-f]{24}$/;
const DB_NAME_SLICE_LEN = 16;
const DB_USER_SLICE_LEN = 12;
const DB_PASS_RANDOM_BYTES = 12;

export interface DatabaseCredentials {
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
}

function assertSafeIdentifier(value: string, label: string): void {
  if (!IDENTIFIER_RE.test(value) || value.length > 64) {
    throw new Error(`${label} "${value}" is not a valid database identifier.`);
  }
}

function assertSafePassword(value: string): void {
  if (!GENERATED_PASSWORD_RE.test(value)) {
    throw new Error('Database password must be generated by the panel.');
  }
}

async function connect(host: DatabaseHost): Promise<mysql.Connection> {
  try {
    return await mysql.createConnection({
      host: host.host,
      port: host.port,
      user: host.username,
      password: host.password,
      connectTimeout: 10_000,
    });
  } catch (error) {
    const code = (error as { code?: string })?.code;
    if (code === 'ECONNREFUSED') {
      throw new Error(`MariaDB missing or not running on ${host.host}:${host.port} (connection refused)`);
    }
    if (code === 'ENOTFOUND') {
      throw new Error(`MariaDB host not found: ${host.host}`);
    }
    throw error instanceof Error ? error : new Error('Failed to connect to the database host');
  }
}

export async function provisionDatabase(host: DatabaseHost, serverId: string): Promise<DatabaseCredentials> {
  const hex = serverId.replace(/-/g, '');
  const dbName = `airlink_${hex.slice(0, DB_NAME_SLICE_LEN)}`;
  const dbUser = `al_${hex.slice(0, DB_USER_SLICE_LEN)}`;
  const dbPass = crypto.randomBytes(DB_PASS_RANDOM_BYTES).toString('hex');

  assertSafeIdentifier(dbName, 'Database name');
  assertSafeIdentifier(dbUser, 'Database user');
  assertSafePassword(dbPass);

  const conn = await connect(host);
  try {
    await conn.execute(`CREATE DATABASE IF NOT EXISTS \`${dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
    await conn.execute(`CREATE USER IF NOT EXISTS '${dbUser}'@'%' IDENTIFIED BY '${dbPass}'`);
    await conn.execute(`ALTER USER '${dbUser}'@'%' IDENTIFIED BY '${dbPass}'`);
    await conn.execute(`GRANT ALL PRIVILEGES ON \`${dbName}\`.* TO '${dbUser}'@'%'`);
    await conn.execute('FLUSH PRIVILEGES');
  } finally {
    await conn.end();
  }

  return { databaseName: dbName, databaseUser: dbUser, databasePassword: dbPass };
}

export async function deprovisionDatabase(host: DatabaseHost, db: ServerDatabase): Promise<void> {
  assertSafeIdentifier(db.databaseName, 'Database name');
  assertSafeIdentifier(db.databaseUser, 'Database user');

  const conn = await connect(host);
  try {
    await conn.execute(`DROP DATABASE IF EXISTS \`${db.databaseName}\``);
    await conn.execute(`DROP USER IF EXISTS '${db.databaseUser}'@'%'`);
    await conn.execute('FLUSH PRIVILEGES');
  } finally {
    await conn.end();
  }
}

export async function rotateDatabasePassword(host: DatabaseHost, db: ServerDatabase): Promise<string> {
  assertSafeIdentifier(db.databaseUser, 'Database user');

  const newPassword = crypto.randomBytes(DB_PASS_RANDOM_BYTES).toString('hex');
  assertSafePassword(newPassword);
  const conn = await connect(host);
  try {
    await conn.execute(`ALTER USER '${db.databaseUser}'@'%' IDENTIFIED BY '${newPassword}'`);
    await conn.execute('FLUSH PRIVILEGES');
  } finally {
    await conn.end();
  }
  return newPassword;
}

export async function testDatabaseHost(host: DatabaseHost): Promise<{ success: boolean; latency?: number; error?: string }> {
  const start = Date.now();
  try {
    const conn = await connect(host);
    await conn.execute('SELECT 1');
    await conn.end();
    return { success: true, latency: Date.now() - start };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Connection failed',
    };
  }
}
